
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.toylang;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int NumeroEntero = 18;
  public static final int Suma = 10;
  public static final int AParentesis = 14;
  public static final int S = 8;
  public static final int M = 7;
  public static final int Calentar = 4;
  public static final int Apagar = 3;
  public static final int Encender = 2;
  public static final int Cocinar = 5;
  public static final int H = 6;
  public static final int EOF = 0;
  public static final int CParentesis = 15;
  public static final int Division = 13;
  public static final int Resta = 11;
  public static final int Linea = 9;
  public static final int error = 1;
  public static final int Punto = 17;
  public static final int Multiplicacion = 12;
  public static final int DosPuntos = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Encender",
  "Apagar",
  "Calentar",
  "Cocinar",
  "H",
  "M",
  "S",
  "Linea",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "AParentesis",
  "CParentesis",
  "DosPuntos",
  "Punto",
  "NumeroEntero"
  };
}

